### ISSUE TITLE
策略：TransSelectEventStrategy 在mac上左键+ctrl 无法多选（mac上此操作等同于右键的菜单调用）

### ISSUE THREAD

**Issue by leonway** [Shiotsukikaedesari/vis-three#2]
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/30642375/212805758-dbb59e2d-09ae-43d5-bbe2-9d9209c2002f.png">

使用window.oncontextmenu=e=>e.preventDefault（）
阻止右键菜单事件后 原来的 click 无法在ctrl+左键时触发。

建议使用alt+左键的组合
vis-three：0.5.3
@vis-three/trans-select-event-strategy:0.5.1

**Comment by Shiotsukikaedesari** [comment]
已从pointerManagerPlugin阻止默认，插件升级到0.6以上
